### ISSUE TITLE
Git flow

### ISSUE THREAD

**Issue by m4v15** [facn2/neuro-games#19]
Hey guys, hope the project is going well

It's really good you're opening issues and stuff, but for someone looking at the project (i.e. me!) there's very little information on what the issues actually mean - there's no descriptions and not much labelling going on.

I would recommend following something similar to [this](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/weeks-10-12/build-sprint/preparing-for-build-sprint.md). Its the standard way we work in FAC. In this case you need to act as your own PO's and identify the user journey you want fulfilled (you've done this already by the looks of your readme). Then it's a good idea to break this down into individual user stories which can then be broken down into the technical tasks.

I would definitely say to do this before getting to stuck into the coding - actually the workflow @Wyrd00 used for 90D app looks really good.

**Comment by KatiaAsh** [comment]
We have add more information in every issues - descriptions and labelling. :smile: 
Thanks for this helpful issue :heart: 
@m4v15 Please have look and close the issue.

**Comment by m4v15** [comment]
Looks great @KatiaAsh thank you!
